name: discordapi

services:

  database:
    container_name: database
    image: postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - database:/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - sql


  nginx:
    image: nginx
    container_name: nginx
    ports:
      - protocol: tcp
        target: 8000
        published: 8881
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx

  user_microservice:
    container_name: user
    build:
      ./user_microservice
    ports:
      - "7000:7000"
    networks:
      - sql
      - nginx

  authorization_microservice:
    container_name: authorization
    build:
      ./authorization_microservice
    ports:
      - "8000:8000"
    networks:
      - sql
      - nginx

  api_gateway:
    container_name: gateway
    build:
      ./api_gateway
    ports:
      - "9000:9000"
    networks:
      - sql
      - nginx

volumes:
  database:

networks:
  sql:
  nginx: