name: "Api CI"

on:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker sql network
        run: docker network create sql
      - name: Build docker nginx network
        run: docker network create nginx
      - name: Build docker containers
        run: docker compose up -d --build
      - name: Check running containers
        run: docker ps -a
#      - name: Run tests
#        run: docker exec user pytest -v -m directly
